### getLevelsOfEducation
- request:
    url: ^/levels$
    method: GET
  response:
    - status: 200
      headers:
        content-type: application/json
      file: data/levelsOfEducation.json

### getUGSNByLevel
- request:
    url: ^/levels/([a-z0-9-]+)/ugsn$
    method: GET
  response:
    - status: 200
      headers:
        content-type: application/json
      file: data/ugsn.json

### getSpecialityByUGSN
- request:
    url: ^/levels/([a-z0-9-]+)/ugsn/([a-z0-9-]+)/specialties$
    method: GET
  response:
    - status: 200
      headers:
        content-type: application/json
      file: data/speciality.json

### getTrainingDirectionBySpeciality
- request:
    url: ^/level/([a-z0-9-]+)/ugsn/([a-z0-9-]+)/specialty/([a-z0-9-]+)/programs$
    method: GET
  response:
    - status: 200
      headers:
        content-type: application/json
      file: data/trainingDirection.json
