### getLevelsOfEducation
- request:
    url: ^/levels$
    method: GET
  response:
    - status: 200
      headers:
        content-type: application/json
      file: data/levelsOfEducation.json

### getUGSN
- request:
    url: ^/levels/([a-z0-9-]+)/ugsn$
    method: GET
  response:
    - status: 200
      headers:
        content-type: application/json
      file: data/ugsn.json

### getSpeciality
- request:
    url: ^/levels/([a-z0-9-]+)/ugsn/([a-z0-9-]+)/specialties$
    method: GET
  response:
    - status: 200
      headers:
        content-type: application/json
      file: data/speciality.json

### getTrainingDirection
- request:
    url: ^/levels/([a-z0-9-]+)/ugsn/([a-z0-9-]+)/specialty/([a-z0-9-]+)/programs$
    method: GET
  response:
    - status: 200
      headers:
        content-type: application/json
      file: data/trainingDirection.json

### getCompetence
- request:
    url: ^/competencies$
    method: GET
  response:
    - status: 200
      headers:
        content-type: application/json
      file: data/competencies.json
